#IN PROGRESS - NOT WORKING YET

name: Cloud Demo Environment Provisioning

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Username'
        required: true
      type:
        description: 'Type of environment to provision'
        required: true
       
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  ECR_REPOSITORY: ld-core-demo
  KUBECTL_VERSION: "v1.23.0"
  LD_API_KEY: ${{ github.event.inputs.type == 'eap' && secrets.LD_EAP_API_KEY || secrets.LD_API_KEY }}
  DEMO_NAMESPACE: ${{ github.event.inputs.name }}-ld-demo


jobs:
  create_ld_project: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./.github/workflows/requirements.txt

