name: "Update All User Environments"

on:
  pull_request:
    branches: [update_all_envs]
    
jobs:
  update-demo-environments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get all branches and loop through them
        run: |
          git fetch --all
          for branch in $(git branch -r | grep -v '\->'); do
            branch=${branch#origin/}
            if [[ $branch == *demoenv* ]]; then
              echo "Branch $branch is a demo environment"
              echo "Updating environment for branch $branch"
            fi
          done