name: Update Demo Environment to v1.2.1

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'User alias or LD env key'
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  ECR_REPOSITORY: ld-core-demo
  KUBECTL_VERSION: "v1.23.0"
  LD_API_KEY: ${{ secrets.LD_API_KEY }} 
  DEMO_NAMESPACE: ${{ github.event.inputs.name }}

jobs:
  update-demo-env-1-2-1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./.github/workflows/requirements.txt

      - name: Install LaunchDarkly CLI
        run: npm install -g @launchdarkly/ldcli

      - name: LD CLI Configure
        run: ldcli config --set access-token ${{ secrets.LD_API_KEY }}
      
      - name: Apply 1.2.1 Update
        run: python ./.github/workflows/v.1.2.1/update_1.2.1.py ${{ env.DEMO_NAMESPACE }}
